# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore
from PyQt5.QtCore import Qt, QRect
from PyQt5.QtWidgets import QMainWindow, QApplication, QPushButton, QWidget

from Utils.Path import rootPath

# 图片所在路径
imgPath = rootPath + "/View/img"

class MyDialog(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(560, 330)
        MainWindow.setWindowFlags(Qt.FramelessWindowHint)  # 无边框
        MainWindow.setStyleSheet("QMainWindow#MainWindow{border-image: url(" + imgPath + "/selfcheck/弹出框_05.png);}")

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")

        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(130, 220, 120, 40))
        self.pushButton.setStyleSheet(u"border-image: url(" + imgPath + "/selfcheck/弹出框_06.png);")

        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(330, 220, 120, 40))
        self.pushButton_2.setStyleSheet(u"border-image: url(" + imgPath + "/selfcheck/弹出框_08.png);")

        MainWindow.setCentralWidget(self.centralwidget)


class MyDialogWidget(QMainWindow, MyDialog):
    def __init__(self, parent=None):
        super(MyDialogWidget, self).__init__(parent)
        self.setupUi(self)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    myWin = MyDialogWidget()
    myWin.show()
    sys.exit(app.exec_())
